#!/usr/bin/env php
<?php

/**
 * This is the main entry point for the global Hyde binary,
 * and is what runs when you run `hyde` from the command line.
 *
 * The binary can be used in two ways:
 * - Anonymous mode: Uses the built-in scaffolding to allow Hyde to be used
 *                   without installation in a directory with just source files.
 * - Proxy mode: Defers to the Hyde installation in the current directory.
 */

// Determine the mode to run in

// If the current directory contains a Hyde binary (that is not this file), run in proxy mode
if (file_exists(getcwd().'/hyde') && realpath(getcwd().'/hyde') !== realpath(__FILE__)) {
    return require_once getcwd().'/hyde';
}

// Otherwise, run in anonymous mode
return (function () {
    // Register the autoloader
    $autoloader = require_once __DIR__.'/vendor/autoload.php';

    // Create the application
    $app = require_once __DIR__.'/app/bootstrap.php';

    // Run the application
    $kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

    $status = $kernel->handle(
        $input = new Symfony\Component\Console\Input\ArgvInput,
        new Symfony\Component\Console\Output\ConsoleOutput
    );

    // Shutdown the application

    $kernel->terminate($input, $status);
    exit($status);
})();
