<?php

declare(strict_types=1);

namespace App\Commands;

use Phar;
use App\Launcher\Project;
use App\Launcher\RuntimeManager;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Process;
use Hyde\RealtimeCompiler\Console\Commands\ServeCommand as BaseServeCommand;

use function sprintf;
use function dirname;
use function var_export;
use function array_merge;
use function escapeshellarg;

/**
 * Serves a Portable project without any PHP installed on the machine.
 *
 * The realtime compiler runs on PHP's built-in web server, which belongs to the
 * CLI SAPI. The executable itself is a micro SAPI and has no built-in server, so
 * the server is started with the PHP CLI runtime that ships inside the
 * executable and is extracted on demand by the {@see RuntimeManager}.
 */
class ServeCommand extends BaseServeCommand
{
    /**
     * Start the server using the bundled PHP runtime.
     *
     * The parent builds a command line that begins with a bare `php`, which would
     * resolve against PATH. We ignore it and build the same command line around
     * the runtime we control, so serving never depends on a system PHP.
     */
    protected function runServerProcess(string $command): void
    {
        $command = sprintf('%s -S %s:%d %s',
            escapeshellarg($this->runtime()->path()),
            $this->getHostSelection(),
            $this->getPortSelection(),
            escapeshellarg($this->getExecutablePath()),
        );

        $this->server = Process::forever()->env($this->getEnvironmentVariables())->start($command, $this->getOutputHandler());
    }

    /** The script the built-in server runs for every request. */
    protected function getExecutablePath(): string
    {
        $default = parent::getExecutablePath();

        if (File::exists($default)) {
            // A source checkout has the realtime compiler on disk already.
            return $default;
        }

        return $this->createServerScript();
    }

    protected function getEnvironmentVariables(): array
    {
        return array_merge(parent::getEnvironmentVariables(), [
            'HYDE_AUTOLOAD_PATH' => $this->resourcePath('vendor/autoload.php'),
            'HYDE_BOOTSTRAP_PATH' => $this->resourcePath('app/bootstrap.php'),
            'HYDE_WORKING_DIR' => $this->laravel->basePath(),
            'HYDE_TEMP_DIR' => $this->temporaryDirectory(),
        ]);
    }

    /**
     * Write a tiny bootstrap script that hands the request over to the realtime compiler.
     *
     * The server process is a plain PHP CLI process, which cannot read the executable
     * itself, so it is pointed at the application archive that the runtime manager
     * extracts alongside the PHP binary.
     */
    protected function createServerScript(): string
    {
        $path = $this->temporaryDirectory().'/bin/server.php';

        $server = var_export($this->resourcePath('vendor/hyde/realtime-compiler/bin/server.php'), true);

        File::ensureDirectoryExists(dirname($path));

        File::put($path, <<<PHP
        <?php

        // Runs the realtime compiler out of the Hyde application archive.
        // Generated by `hyde serve`; safe to delete.

        return require $server;
        PHP);

        return $path;
    }

    /**
     * Resolve a path inside the application, whether it is on disk or inside the extracted archive.
     *
     * Both branches answer in the launcher's canonical representation. The archive branch
     * has no choice — a `phar://` URL is written with forward slashes — and the branch
     * that reads the disk used to answer in the platform's own spelling instead, so
     * the server subprocess was handed `D:\a\cli\vendor\autoload.php` next to
     * three paths that had been canonicalized. One environment, one spelling.
     */
    protected function resourcePath(string $path): string
    {
        if (Phar::running() !== '') {
            return 'phar://'.$this->runtime()->archivePath().'/'.$path;
        }

        return Project::canonicalize(dirname(__DIR__, 2).'/'.$path);
    }

    /** The writable directory the executable uses for everything it cannot keep inside itself. */
    protected function temporaryDirectory(): string
    {
        return dirname($this->laravel->storagePath(), 2);
    }

    protected function runtime(): RuntimeManager
    {
        return $this->laravel->make(RuntimeManager::class);
    }
}
