name: Build Documentation

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Create site from Readme
        run: |
          mkdir _pages
          mv README.md _pages/index.md
          touch _pages/manual.html # Make Hyde aware of the manual

      - name: Move Hyde config
        run: mv .github/docs/hyde.yml hyde.yml

      - uses: hydephp/action@master

      - name: Build manual
        run: php bin/build-manual.php

      - name: Move manual
        run: |
          mv docs/manual/manual.html _site/manual.html
          mv docs/manual/manual.xml _site/manual.xml
          mv docs/manual/manual.md _site/manual.md
          cp .github/docs/asset/manual.xsl _site/manual.xsl
          sed -i '1a<?xml-stylesheet type="text/xsl" href="manual.xsl"?>' _site/manual.xml

      - name: Move analytics page
        run: |
          mkdir _site/repo
          cp .github/docs/analytics.html _site/repo/analytics.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: pages-deployment
        uses: actions/deploy-pages@v4
